#启动配置
vertx:
  #激活的环境
  profiles:
    active: dev
  #应用信息
  application:
    name: appName
  #vertx配置
  vertxOptions:
    #设置eventloop数量，默认是可用核心的两倍
    eventLoopPoolSize: 20
    #设置eventbus参数
    eventBusOptions:
      #连接超时时间(ms)
      connectTimeout: 50000
  deploymentOptions:
    instances: 2

testVerticle:
  deploymentOptions:
    instances: 1

#a: 1
b: test
e:
  f:
    g:
      y: 1000